### ISSUE TITLE
React todo example not working

### ISSUE THREAD

**Issue by josx** [feathersjs-ecosystem/feathers-reactive#42]
Example on https://github.com/feathersjs/feathers-reactive/tree/master/examples/react-todos
it is not working 

Error:
```
steal.js:6363 Error loading "client" at http://localhost:3030/client.js
http://localhost:3030/client.js:55:7: Unexpected token < undefined(anonymous function) 
@ steal.js:6363tryCatchReject 
@ steal.js:1188runContinuation1 
@ steal.js:1147Rejected.when 
@ steal.js:968Pending.run 
@ steal.js:826Scheduler._drain 
@ steal.js:102Scheduler.drain 
@ steal.js:67run 
@ steal.js:273
```

**Comment by daffl** [comment]
Did you run `npm install` in the `react-todos` folder?

**Comment by josx** [comment]
Yes, but just in the ```react-todos``` folder.
It seems to not understand jsx syntax (maybe something to do with steal-jsx plugin).
Tested on Chromium version 53.0.2785.113 and Firefox 45.3.0

**Comment by daffl** [comment]
Got it, I could reproduce it now as well, thank you! I locked the Steal version so it should be working again now.

**Comment by josx** [comment]
Great thanks! (so was a dependecies upgrade problem, so it is not compatible with newer steal versions)

**Comment by daffl** [comment]
It looks like it. I'll have to look into why (and then probably just upgrade to 1.0)

**Comment by josx** [comment]
Just a clue about this, probles appear after upgrade from steal 0.10.39 to 0.10.40.

Here discussion and commit:
https://github.com/stealjs/steal/issues/867
https://github.com/stealjs/steal/commit/6f75236e0ae760a86739b338d544fd0afeef58a0
