### ISSUE TITLE
Dove Support

### ISSUE THREAD

**Issue by forgot** [feathersjs-ecosystem/feathers-reactive#179]
I'm attempting to update `feathers-reactive`, so I thought I'd open an issue for discussion.

I updated the dependencies to `5.0.0-pre.4`, made a few changes, and now it passes all the tests. The problem I'm running into now has to do with types. I'm not quite sure how update `index.d.ts` to allow the package to work correctly.

Even when I think I have the types correct, I end up with the error `Module not found: Error: Can't resolve 'feathers-reactive' in ...`

[Here's](https://github.com/forgot/feathers-reactive/tree/Dove) a link to my fork if anyone can point me in the right direction.

**Comment by daffl** [comment]
The problem is probably in https://github.com/forgot/feathers-reactive/blob/Dove/index.d.ts#L34 since all the module locations and namespaces changed. Ideally this would be an opportunity to migrate this repo to TypeScript as well since RxJS already is anyway. Then it would probably just work ™️  without any workarounds or hacks.

**Comment by RuneSP** [comment]
After updating feathers to 5.0.0-pre.18 I'm getting this error when trying to use the service method:

```
global.error.handler.ts:25 Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach')
    at Feathers.mixin (index.js:65:1)
    at application.js:78:1
    at Array.forEach (<anonymous>)
    at Feathers.use (application.js:78:1)
    at Feathers.service (application.js:53:1)
```

Code:

```
        const service = feathers()
            .configure(socketio(this._socket))
            .configure(feathersRx({                       
                idField: '_id'
            }))
            .service('test');

```

**Comment by forgot** [comment]
That error is caused by the function at [this line](https://github.com/feathersjs-ecosystem/feathers-reactive/blob/9a6e620ff4abbaac5618c3d33ab53ec5e1a91b5b/src/index.js#L51). In Feathers 5.0, the `app` no longer has a `methods` property so the `forEach` throws an error. To my understanding, these are now exported as `defaultServiceMethods` [here](https://github.com/feathersjs/feathers/blob/54de749a0b392c7da726c668002b50cafaca530c/packages/feathers/src/service.ts#L6).

**Comment by claustres** [comment]
I think there is also another issue, this [imported file](https://github.com/feathersjs-ecosystem/feathers-reactive/blob/master/src/utils.js#L2) does not seem to exist anymore in Feathers v5, it should probably be something like:
`import { _ } from '@feathersjs/commons'`

**Comment by claustres** [comment]
I've started a PR, would you mind testing @forgot @RuneSP ? Thanks for feedback

**Comment by daffl** [comment]
This has been published now as 0.10.0 - we might do another bigger pass migrating to TypeScript but this should work now already.
